require 'robot_arm'
robot_arm:load_level('exercise 3')
robot_arm:grab('exercise 3')
robot_arm:move_right('exercise 3')
robot_arm:drop('exercise3')
robot_arm:move_left('exercise 3')
robot_arm:grab('exercise 3')
robot_arm:move_right('exercise 3')
robot_arm:drop('exercise3')
robot_arm:move_left('exercise 3')
robot_arm:grab('exercise 3')
robot_arm:move_right('exercise 3')
robot_arm:drop('exercise3')
robot_arm:move_left('exercise 3')
robot_arm:grab('exercise 3')
robot_arm:move_right('exercise 3')
robot_arm:drop('exercise3')